"""Init5

Revision ID: 9f8580ed66ec
Revises: d05d3541e187
Create Date: 2023-11-16 10:49:50.924673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8580ed66ec'
down_revision = 'd05d3541e187'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
