"""Init6

Revision ID: 9bd836d09e60
Revises: 9f8580ed66ec
Create Date: 2023-11-17 21:06:12.018606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd836d09e60'
down_revision = '9f8580ed66ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
