"""Init2

Revision ID: fd5646d420c3
Revises: 8933c59879e5
Create Date: 2023-11-12 11:43:44.531142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5646d420c3'
down_revision = '8933c59879e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('location', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
